### ISSUE TITLE
环境

### ISSUE THREAD

**Issue by enhuishu** [millieXie/FusionMamba#17]
到这一步pip install causal_conv1d==1.0.0 # causal_conv1d-1.0.0+cu118torch1.13cxx11abiFALSE-cp38-cp38-linux_x86_64.whl
就报错了，前面按照
conda create -n FusionMamba python=3.8
conda activate FusionMamba
pip install torch==1.13.0 torchvision==0.14.0 torchaudio==0.13.0 --extra-index-url [https://download.pytorch.org/whl/cu117 ](https://download.pytorch.org/whl/cu117%C2%A0)
pip install packaging pip install timm==0.4.12
pip install pytest chardet yacs termcolor
pip install submitit tensorboardX
pip install triton==2.0.0

linux_x86_64.whl
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting causal_conv1d==1.0.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f8/33/f43df821036ad5dd64a4697f37459c28855e5a387dfdae10c8b1d6053b32/causal_conv1d-1.0.0.tar.gz (6.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-fyuezqz1/causal-conv1d_1a682a89ed024650a350d68898e0894c/setup.py", line 102, in <module>
          raise RuntimeError(
      RuntimeError: causal_conv1d is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.
      
      
      torch.__version__  = 1.13.0+cu117
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by millieXie** [comment]
跟你的pytorch框架版本和cuda版本有关 确保你的系统已安装Python 3.8或更高版本。cuda好像是要再12.0以上 如果还没跑通可以再来问我

**Comment by enhuishu** [comment]
多谢作者，环境问题已解决，不过用于医学数据集的话，这个目录该怎么调整呢，
![image](https://github.com/user-attachments/assets/45b1e519-af0e-450d-b103-6861fe726b1d)

**Comment by millieXie** [comment]
你按照那个KAIST的数据结构就可以，然后医学的话需要先转成Y通道进行输入。代码暂时没有了，我盘坏了暂时拿不出来代码。你先自己搞一下吧。然后哈，你可以把我的网络抠出来然后用别人的数据加载代码来跑，只要保证输入输出的处理一致就可以啦，细节可以不用在意。推荐SwinFusion或者CDDFuse哦~最好是jpg格式进行输入~前辈们做的比较好，你可以看一下他们的代码。

**Comment by li20220125** [comment]
> 到这一步pip install causal_conv1d==1.0.0 # causal_conv1d-1.0.0+cu118torch1.13cxx11abiFALSE-cp38-cp38-linux_x86_64.whl 就报错了，前面按照 conda create -n FusionMamba python=3.8 conda activate FusionMamba pip install torch==1.13.0 torchvision==0.14.0 torchaudio==0.13.0 --extra-index-url [https://download.pytorch.org/whl/cu117 ](https://download.pytorch.org/whl/cu117%C2%A0) pip install packaging pip install timm==0.4.12 pip install pytest chardet yacs termcolor pip install submitit tensorboardX pip install triton==2.0.0
> 
> linux_x86_64.whl Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple Collecting causal_conv1d==1.0.0 Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f8/33/f43df821036ad5dd64a4697f37459c28855e5a387dfdae10c8b1d6053b32/causal_conv1d-1.0.0.tar.gz (6.4 kB) Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [11 lines of output] Traceback (most recent call last): File "", line 2, in File "", line 34, in File "/tmp/pip-install-fyuezqz1/causal-conv1d_1a682a89ed024650a350d68898e0894c/setup.py", line 102, in raise RuntimeError( RuntimeError: causal_conv1d is only supported on CUDA 11.6 and above. Note: make sure nvcc has a supported version by running nvcc -V.
> 
> ```
>   torch.__version__  = 1.13.0+cu117
>   
>   
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.

您好，请问一下，这个是怎么解决的，谢谢

**Comment by enhuishu** [comment]
> pip install causal_conv1d==1.0.0 # causal_conv1d-1.0.0+cu118torch1.13cxx11abiFALSE-cp38-cp38-linux_x86_64.whl

参考  ： 
https://blog.csdn.net/weixin_44292425/article/details/136649809?ops_request_misc=&request_id=&biz_id=102&utm_term=pip%20install%20causal_conv1d==1.0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduweb~default-1-136649809.142^v100^pc_search_result_base8&spm=1018.2226.3001.4187

**Comment by li20220125** [comment]
好嘞好嘞，谢谢啦

**Comment by li20220125** [comment]
这个环境必须在lunix下面吗，windows可以不可以呀，麻烦您了

> > pip install causal_conv1d==1.0.0 # causal_conv1d-1.0.0+cu118torch1.13cxx11abiFALSE-cp38-cp38-linux_x86_64.whl
> 
> 参考 ： [https://blog.csdn.net/weixin_44292425/article/details/136649809?ops_request_misc=&request_id=&biz_id=102&utm_term=pip%20install%20causal_conv1d==1.0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduweb~default-1-136649809.142^v100^pc_search_result_base8&spm=1018.2226.3001.4187](https://blog.csdn.net/weixin_44292425/article/details/136649809?ops_request_misc=&request_id=&biz_id=102&utm_term=pip%20install%20causal_conv1d==1.0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduweb~default-1-136649809.142%5Ev100%5Epc_search_result_base8&spm=1018.2226.3001.4187)

**Comment by enhuishu** [comment]
不知道，你可以试试








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年12月30日(周一) 晚上8:31写道:

  

 
这个环境必须在lunix下面吗，windows可以不可以呀，麻烦您了
   
pip install causal_conv1d==1.0.0 # causal_conv1d-1.0.0+cu118torch1.13cxx11abiFALSE-cp38-cp38-linux_x86_64.whl
  
参考 ： https://blog.csdn.net/weixin_44292425/article/details/136649809?ops_request_misc=&amp;request_id=&amp;biz_id=102&amp;utm_term=pip%20install%20causal_conv1d==1.0&amp;utm_medium=distribute.pc_search_result.none-task-blog-2allsobaiduweb~default-1-136649809.142^v100^pc_search_result_base8&amp;spm=1018.2226.3001.4187

**Comment by quyuan2744** [comment]
> 多谢作者，环境问题已解决，不过用于医学数据集的话，这个目录该怎么调整呢， ![image](https://private-user-images.githubusercontent.com/185164695/396806645-45b1e519-af0e-450d-b103-6861fe726b1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0NzU1ODksIm5iZiI6MTczNjQ3NTI4OSwicGF0aCI6Ii8xODUxNjQ2OTUvMzk2ODA2NjQ1LTQ1YjFlNTE5LWFmMGUtNDUwZC1iMTAzLTY4NjFmZTcyNmIxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExMFQwMjE0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjVkYWI3OGIyMzM3MmZlZGMxMmYzNmIyNzJlNTBiMGIyMzRiYWZiMjZkYmE3ZmUwZWFmYTgyMmIxMDc2OTY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.V7h7aiuLhKne_c3gR3D58EchYg4BiMx-5cTQWLE246w)

请问 数据要怎么处理呀

**Comment by quyuan2744** [comment]
> 你按照那个KAIST的数据结构就可以，然后医学的话需要先转成Y通道进行输入。代码暂时没有了，我盘坏了暂时拿不出来代码。你先自己搞一下吧。然后哈，你可以把我的网络抠出来然后用别人的数据加载代码来跑，只要保证输入输出的处理一致就可以啦，细节可以不用在意。推荐SwinFusion或者CDDFuse哦~最好是jpg格式进行输入~前辈们做的比较好，你可以看一下他们的代码。

可以提供代码吗

**Comment by jellybean05** [comment]
> 多谢作者，环境问题已解决，不过用于医学数据集的话，这个目录该怎么调整呢， ![image](https://github.com/user-attachments/assets/45b1e519-af0e-450d-b103-6861fe726b1d)



> 多谢作者，环境问题已解决，不过用于医学数据集的话，这个目录该怎么调整呢， ![image](https://github.com/user-attachments/assets/45b1e519-af0e-450d-b103-6861fe726b1d)

请问复现完代码能运行了吗
