### ISSUE TITLE
Net-2024-12-29-16-27-20.log

### ISSUE THREAD

**Issue by GeminiYJL** [millieXie/FusionMamba#19]
(FusionMamba) root@autodl-container-c757409664-dea82beb:~/autodl-tmp/FusionMamba-main# python train.py
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    setup_logger(logpath)
  File "/root/autodl-tmp/FusionMamba-main/logger.py", line 20, in setup_logger
    logging.basicConfig(level=log_level, format=FORMAT, filename=logfile)
  File "/root/miniconda3/envs/FusionMamba/lib/python3.8/logging/__init__.py", line 1988, in basicConfig
    h = FileHandler(filename, mode)
  File "/root/miniconda3/envs/FusionMamba/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "/root/miniconda3/envs/FusionMamba/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/FusionMamba-main/logs/Net-2024-12-29-16-27-20.log'
请问这个问题怎么解决呢

**Comment by millieXie** [comment]
你需要创建一个log文件夹

**Comment by jellybean05** [comment]
> 你需要创建一个log文件夹

请问自己创建这个log文件夹里面应该放什么呢
